name: Build Book

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-book:
    runs-on: ubuntu-latest

    container:
      image: sahilkale1/fw_hw_book_docker_img:latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Build the book
    - name: Build the book
      run: python3 scripts/build_book.py --build_teaser

    # Step 3: Archive the built book
    - name: Archive built book
      if: success()
      run: |
        mkdir -p artifacts
        cp output/main.pdf artifacts/
        cp output/teaser.pdf artifacts/

    # Step 4: Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-book
        path: artifacts
