name: Code Format Check

on:
  push:
    branches:
      - main 
  pull_request:
    branches: [ main ]

jobs:
  check-format:
    # Specify the Docker container for the job
    container:
      image: sahilkale1/fw_hw_book_docker_img:latest

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 
        with:
          submodules: recursive
      - name: Check Code Format
        run: python3 scripts/format.py --dry-run
